### ISSUE TITLE
psycopg2.ProgrammingError in TravisCI

### ISSUE THREAD

**Issue by jeremy-leveque** [coddingtonbear/django-mailbox#165]
Hello,

I have installed `django-mailbox` locally by added it into `INSTALLED_APPS` and then ran `./manage.py migrate django-mailbox`. It works fine.
But now I want to deploy my modifications through TravisCI. Sadly, it does not work.

Here is the script I run : 
````
#!/bin/bash
set -e

cd ./backend

python manage.py migrate
python manage.py collectstatic --noinput
python manage.py test

cd ..
````

And here are the Travis logs : 
````
$ CI_scripts/run_backend.sh
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "django_mailbox_mailbox" does not exist
LINE 1: ...ve", "django_mailbox_mailbox"."last_polling" FROM "django_ma...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/Co-bble/[secure]/backend/backend/urls.py", line 22, in <module>
    url(r'^tool/', include('tools.tickets.urls')),
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/Co-bble/[secure]/backend/tools/tickets/urls.py", line 3, in <module>
    from .views import (
  File "/home/travis/build/Co-bble/[secure]/backend/tools/tickets/views.py", line 36, in <module>
    mailbox = Mailbox.objects.get(name="OVH Mails")
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 373, in get
    num = len(clone)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_mailbox_mailbox" does not exist
LINE 1: ...ve", "django_mailbox_mailbox"."last_polling" FROM "django_ma...
````

Can someone help me please ?

Thanks in advance

**Comment by ad-m** [comment]
What is ``CI_scripts/run_backend.sh``? It looks as if migrations were not entered. Maybe you use two databases in a different place? Are you sure about the application configuration? 

See:

- our TravisCI configuration: https://github.com/coddingtonbear/django-mailbox/blob/master/.travis.yml 
- configuration in my application: https://github.com/watchdogpolska/feder/blob/master/.travis.yml

**Comment by jeremy-leveque** [comment]
Thank you for replying.
`CI_scripts/run_backend.sh` is the script I put at the beginning of my question 
````
#!/bin/bash
set -e

cd ./backend

python manage.py migrate
python manage.py collectstatic --noinput
python manage.py test

cd ..
````

I only use one database and I'm pretty sure about the application configuration : it worked well before I try to use `django-mailbox`. 

I look at your configurations

**Comment by ad-m** [comment]
@jeremy-leveque , have you added ```django-mailbox``` to ````INSTALLED_APPS```? Do you can dump rows of ```django_migrations``` table?

**Comment by ad-m** [comment]
@jeremy-leveque , have you added ```django_mailbox``` to ```INSTALLED_APPS``` ? Try ```python manage.py diffsettings | grep "INSTALLED_APPS"```.

Do you can dump rows of ```django_migrations``` table?

**Comment by jeremy-leveque** [comment]
I think that the `django_mailbox` migrations are not found by Travis when it builds.
When I build locally, I get the following warning : 
````
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
````

When I run `manage.py makemigrations`, it creates a migration for `django_mailbox`. 

Do you have a clue ?

**Comment by ad-m** [comment]
@jeremy-leveque , paste here created migrations, please.

**Comment by jeremy-leveque** [comment]
This one is created : 

````
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0006_mailbox_last_polling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'verbose_name': 'Mailbox', 'verbose_name_plural': 'Mailboxes'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'E-mail message', 'verbose_name_plural': 'E-mail messages'},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': 'Message attachment', 'verbose_name_plural': 'Message attachments'},
        ),
    ]
````

**Comment by ad-m** [comment]
This is only altering metadata of model. The errors is related to missing table. 

@jeremy-leveque , 

- which version of django-migrations do you use? Did you use ```.tar.gz``` or ```.whl``` or ```git://``` to install? 
- Do you can dump rows of ```django_migrations``` table in PostgreSQL?

**Comment by jeremy-leveque** [comment]
I have installed django and django-migrations via `git://`. I use Django 1.11

Here are some rows of `django_migrations` table in PostgreSQL : 
````
74	django_mailbox	0001_initial	2018-01-05 10:57:51.308855+00
75	django_mailbox	0002_add_eml_to_message	2018-01-05 10:57:51.336519+00
76	django_mailbox	0003_auto_20150409_0316	2018-01-05 10:57:51.352877+00
77	django_mailbox	0004_bytestring_to_unicode	2018-01-05 10:57:51.382733+00
78	django_mailbox	0005_auto_20160523_2240	2018-01-05 10:57:51.401841+00
79	django_mailbox	0006_mailbox_last_polling	2018-01-05 10:57:51.421974+00
80	emails	0001_initial	2018-01-07 14:57:25.344021+00
81	emails	0002_auto_20171206_1756	2018-01-07 14:57:25.432946+00
````

**Comment by ad-m** [comment]
@jeremy-leveque , do you have django-mailbox tables?

**Comment by jeremy-leveque** [comment]
Yes, locally, I have them. All works fine locally, but Travis fails

Le dim. 7 janv. 2018 à 17:05, Adam Dobrawy <notifications@github.com> a
écrit :

**Comment by ad-m** [comment]
@jeremy-leveque , do you use different settings for TravisCI & locally?

**Comment by AdrienAgnel** [comment]
Hi @ad-m, i'm trying to solve the issue with @jeremy-leveque, we don't have different setting for TravisCI & local dev and I also can't get it to work locally starting from jeremy's branch.

I first installed the new requirements with django-mailbox and then tried `python manage.py migrate django_mailbox`, which outputs the same error as above: `django.db.utils.ProgrammingError: relation "django_mailbox_mailbox" does not exist
LINE 1: ...ve", "django_mailbox_mailbox"."last_polling" FROM "django_ma...`

Looking at the error stack: `File "/home/travis/build/Co-bble/[secure]/backend/tools/tickets/views.py", line 36, in <module>
    mailbox = Mailbox.objects.get(name="OVH Mails")` if I comment the reference to Mailbox in our application code then it becomes possible to run `python manage.py migrate django_mailbox` and then when uncommenting it the application work, unfortunately this is not reproducible in TravisCi...

When trying to investigate we found some similar errors on other projects, here is one of them maybe you will see something that we didn't get : https://github.com/jazzband/django-constance/issues/229

**Comment by ad-m** [comment]
Do you can provide line 30-40 of ```home/travis/build/Co-bble/[secure]/backend/tools/tickets/views.py```?

**Comment by AdrienAgnel** [comment]
Hi Adam, here is the file:
```python
# other imports here...
from django_mailbox.models import Mailbox

mailbox = Mailbox.objects.get(name="OVH Mails")  # this is line 36


class TicketList(generics.ListCreateAPIView):
    filter_fields = ('ticket_state', 'ticket_state__type',
                     'ticket_description')
    permission_classes = [Or(IsAuthenticadedRequest, IsPostRequest)]

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return PostTicketSerializer
        return GetTicketSerializer

    def get_queryset(self):
        ticket_number = self.request.query_params.get('ticket_number', None)
        mailbox.get_new_mail(condition=None)
```

your question triggered a doubt, we moved the faulty mailbox item in the __init__ of the TicketList class and this solved our issue

We now have:
```python
class TicketList(generics.ListCreateAPIView):
    filter_fields = ('ticket_state', 'ticket_state__type',
                     'ticket_description')
    permission_classes = [Or(IsAuthenticadedRequest, IsPostRequest)]

    def __init__(self):
        self.mailbox = Mailbox.objects.get(name="OVH Mails")

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return PostTicketSerializer
        return GetTicketSerializer

    def get_queryset(self):
        # Get new mails
        self.mailbox.get_new_mail(condition=None)
```
django_mailbox migrations run without any problem.

I have to confess that I don't really see the link between the error and the solution we came up with. Do you have any clue why defining `mailbox` the first way leads to a Programming Error when running migrations ?
Thanks for your help !

**Comment by ad-m** [comment]
I think it's still a bad idea to make queries to the database in views.py directly and that seems to be a problem. If you define variable in views.py this means that the code is executed when parsing urls.py which import views.py. At this time, however, not all Django components are loaded correctly. This leads not to the expected results. Django provides eg. ```AppConfig.ready()``` to provide way to execute queries a bit later.

I think more django-way is write something like:
```
class TicketList(generics.ListCreateAPIView):
    filter_fields = ('ticket_state', 'ticket_state__type',
                     'ticket_description')
    permission_classes = [Or(IsAuthenticadedRequest, IsPostRequest)]

    def dispatch(self, request, *args, **kwargs):
        self.mailbox = Mailbox.objects.get(name="OVH Mails")
        super(TicketList, self).__init__(*args, **kwargs)
```
The Django view classes are a bit specific, and this format better reflects intentions IMO. See what happen in ```as_view``` method of ```View``` at http://ccbv.co.uk/projects/Django/1.11/django.views.generic.base/TemplateView/#as_view .

**Comment by jeremy-leveque** [comment]
@ad-m Thank you very much for your replies, it has been very helpful ! It now works well 🍾 

I close the issue.
