### ISSUE TITLE
Error getting message text

### ISSUE THREAD

**Issue by olivtree** [coddingtonbear/django-mailbox#167]
Hi, 
I am trying to get message text but in some emails it's returned the following error:
```
>>>from django_mailbox.models import Message
>>>message = Message.objects.get(id=560)
>>>message.text
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/django_mailbox/models.py", line 602, in text
    ).replace('=\n', '').strip()
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/django_mailbox/models.py", line 726, in get_email_object
    return self._rehydrate(flat)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/django_mailbox/models.py", line 622, in _rehydrate
    self._rehydrate(part)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/django_mailbox/models.py", line 651, in _rehydrate
    attachment.document.read()
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/storages/backends/s3boto.py", line 155, in read
    return super(S3BotoStorageFile, self).read(*args, **kwargs)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/django/core/files/utils.py", line 16, in <lambda>
    read = property(lambda self: self.file.read)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/storages/backends/s3boto.py", line 141, in _get_file
    self.key.get_contents_to_file(self._file)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/boto/s3/key.py", line 1650, in get_contents_to_file
    response_headers=response_headers)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/boto/s3/key.py", line 1482, in get_file
    query_args=None)
  File "/home/ubuntu/sup.dev/local/lib/python3.4/site-packages/boto/s3/key.py", line 1536, in _get_file_internal
    fp.write(bytes)
TypeError: string argument expected, got 'bytes'
```

What can I do to get the original text in case this error is returned?

Thanks

**Comment by ad-m** [comment]
Which version of python? Which version of Django? Which storage backend?

**Comment by ad-m** [comment]
Which version of python? Which version of Django? Which storage backend?

**Comment by olivtree** [comment]
Python 3.4 and Django 1.8.2

**Comment by olivtree** [comment]
@coddingtonbear is this what you ask for?
>>> import boto
>>> boto.Version
'2.38.0'

**Comment by coddingtonbear** [comment]
Sorry for the delay, @olivtree, that is what I was looking for.  I did a little research and did find at least a few google results matching that error message from boto.s3 (https://github.com/coagulant/django-storages-py3/issues/6, https://stackoverflow.com/questions/25847031/typeerror-string-argument-expected-got-bytes-python-3) and I'm not totally sure what's up, but I'm betting it has something to do with Python 3 support in django-storages and/or boto.  I have a couple ideas (both of which I'm sure you've already thought of):

1) Make sure you're on a fairly modern version of `django-storages`.  It's possible that maybe this was a bug in an earlier version of `django-storages`.
2) _Maybe_ try boto3 instead of the standard boto.  I'm less sure if that'd help anything, but it does seem to be the version of Boto currently in development.

Either way, though, I'm fairly sure this is going to turn out to be a problem outside of this specific library -- this library just asks Django to give us a file, and the error being raised is happening a few modules deeper if you look carefully at your traceback.  That said -- I'm totally willing to help you troubleshoot if you hit me up on Freenode (I'm coddingtonbear there, too).

(If this does turn out to be a problem in django-mailbox, I'll be terribly surprised and embarassed and will apologize profusely before re-opening this ticket.)

Cheers!
