### ISSUE TITLE
error: Invalid credentials (Failure)

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#172]
[I went through the following steps for generating the access token](https://github.com/google/gmail-oauth2-tools/wiki/OAuth2DotPyRunThrough)  
  
When I try to poll the mailbox from django admin view, I get the following error, which I suspect is because the python-social-auth module doesnt contain the AccessToken but I cant find out how to store the AccessToken in it.  
  
`Traceback (most recent call last):  
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)  
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response  
    response = self.process_exception_by_middleware(e, request)  
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response  
    response = wrapped_callback(request, *callback_args, **callback_kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/admin/options.py", line 574, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func  
    response = view_func(request, *args, **kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)  
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)  
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/admin/options.py", line 1596, in changelist_view  
    response = self.response_action(request, queryset=cl.get_queryset(request))  
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/admin/options.py", line 1330, in response_action  
    response = func(self, request, queryset)  
  File "/usr/local/lib/python3.5/dist-packages/django_mailbox/admin.py", line 26, in get_new_mail
    mailbox.get_new_mail()  
  File "/usr/local/lib/python3.5/dist-packages/django_mailbox/models.py", line 409, in get_new_mail
    connection = self.get_connection()  
  File "/usr/local/lib/python3.5/dist-packages/django_mailbox/models.py", line 208, in get_connection
    conn.connect(self.username, self.password)  
  File "/usr/local/lib/python3.5/dist-packages/django_mailbox/transports/gmail.py", line 18, in connect  
    typ, msg = self.server.login(username, password)  
  File "/usr/lib/python3.5/imaplib.py", line 582, in login  
    raise self.error(dat[-1])  
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'`

**Comment by modernNeo** [comment]
[full_error_log.txt](https://github.com/coddingtonbear/django-mailbox/files/1778337/full_error_log.txt)
