### ISSUE TITLE
Password encode

### ISSUE THREAD

**Issue by olivtree** [coddingtonbear/django-mailbox#181]
Hi, i insert a password with lower and uppercase characters and numbers, and the getmail command returned the folllowing error:

```
Traceback (most recent call last):
  File ".../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".../lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File ".../lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File ".../lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File ".../lib/python3.4/site-packages/django_mailbox/management/commands/getmail.py", line 24, in handle
    messages = mailbox.get_new_mail()
  File ".../lib/python3.4/site-packages/django_mailbox/models.py", line 409, in get_new_mail
    connection = self.get_connection()
  File ".../lib/python3.4/site-packages/django_mailbox/models.py", line 191, in get_connection
    elif self.type == 'imap':
  File ".../lib/python3.4/site-packages/django_mailbox/models.py", line 151, in type
    scheme = self._protocol_info.scheme.lower()
  File ".../lib/python3.4/site-packages/django_mailbox/models.py", line 118, in _protocol_info
    return urlparse(self.uri)
  File ".../lib/python3.4/urllib/parse.py", line 293, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File ".../lib/python3.4/urllib/parse.py", line 366, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
['ValueError: Invalid IPv6 URL', '  File "raven/contrib/django/management/__init__.py", line 41, in new_execute', '  File "django/core/management/base.py", line 444, in execute', '  File "django_mailbox/management/commands/getmail.py", line 24, in handle', '  File "django_mailbox/models.py", line 409, in get_new_mail', '  File "django_mailbox/models.py", line 191, in get_connection', '  File "django_mailbox/models.py", line 151, in type', '  File "django_mailbox/models.py", line 118, in _protocol_info', '  File "urllib/parse.py", line 293, in urlparse', '  File "urllib/parse.py", line 366, in urlsplit']
b'[\'ValueError: Invalid IPv6 URL\', \'  File "raven/contrib/django/management/__init__.py", line 41, in new_execute\', \'  File "django/core/management/base.py", line 444, in execute\', \'  File "django_mailbox/management/commands/getmail.py", line 24, in handle\', \'  File "django_mailbox/models.py", line 409, in get_new_mail\', \'  File "django_mailbox/models.py", line 191, in get_connection\', \'  File "django_mailbox/models.py", line 151, in type\', \'  File "django_mailbox/models.py", line 118, in _protocol_info\', \'  File "urllib/parse.py", line 293, in urlparse\', \'  File "urllib/parse.py", line 366, in urlsplit\']'
['ValueError: Invalid IPv6 URL', '  File ".../manage.py", line 10, in <module>', '  File "django/core/management/__init__.py", line 338, in execute_from_command_line', '  File "django/core/management/__init__.py", line 330, in execute', '  File "django/core/management/base.py", line 393, in run_from_argv', '  File "raven/contrib/django/management/__init__.py", line 41, in new_execute', '  File "django/core/management/base.py", line 444, in execute', '  File "django_mailbox/management/commands/getmail.py", line 24, in handle', '  File "django_mailbox/models.py", line 409, in get_new_mail', '  File "django_mailbox/models.py", line 191, in get_connection', '  File "django_mailbox/models.py", line 151, in type', '  File "django_mailbox/models.py", line 118, in _protocol_info', '  File "urllib/parse.py", line 293, in urlparse', '  File "urllib/parse.py", line 366, in urlsplit']
b'[\'ValueError: Invalid IPv6 URL\', \'  File ".../manage.py", line 10, in <module>\', \'  File "django/core/management/__init__.py", line 338, in execute_from_command_line\', \'  File "django/core/management/__init__.py", line 330, in execute\', \'  File "django/core/management/base.py", line 393, in run_from_argv\', \'  File "raven/contrib/django/management/__init__.py", line 41, in new_execute\', \'  File "django/core/management/base.py", line 444, in execute\', \'  File "django_mailbox/management/commands/getmail.py", line 24, in handle\', \'  File "django_mailbox/models.py", line 409, in get_new_mail\', \'  File "django_mailbox/models.py", line 191, in get_connection\', \'  File "django_mailbox/models.py", line 151, in type\', \'  File "django_mailbox/models.py", line 118, in _protocol_info\', \'  File "urllib/parse.py", line 293, in urlparse\', \'  File "urllib/parse.py", line 366, in urlsplit\']'
```

In the settings of mailbox says "Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).". But uppercase characters and numbers are not special characters. How are uppercase characters and number "encoded"?

**Comment by ad-m** [comment]
Do you can specify what password do you know as broken? Do you can provide full URL? I use fg. lowercase & uppercase letters in production password.

**Comment by pfouque** [comment]
It's probably related to the encoding, username and password need to be URL encoded separately and then combined to produce a standard basic auth URL:
`imap+ssl://<urlencoded_login>:<urlencoded_password>@imap.gmail.com?folder=MyFolder`

I will close this issue but feel free to re-open one (with more details ideally)
