### ISSUE TITLE
No Migrations

### ISSUE THREAD

**Issue by Bastilla123** [coddingtonbear/django-mailbox#209]
Hello,

i install this app:

pip3 install django-mailbox
Requirement already satisfied: django-mailbox in ./neueumgebung/lib/python3.7/site-packages (4.8.0)
Requirement already satisfied: six>=1.6.1 in ./neueumgebung/lib/python3.7/site-packages (from django-mailbox) (1.12.0)

and my settings.py:

INSTALLED_APPS = [
    'django-mailbox',
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'homepage',
    'ueberschussrechnung',
]

but everytime i make:

python3 manage.py migrate django-mailbox
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sebastian/PycharmProjects/Easyheb/neueumgebung/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sebastian/PycharmProjects/Easyheb/neueumgebung/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/sebastian/PycharmProjects/Easyheb/neueumgebung/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/sebastian/PycharmProjects/Easyheb/neueumgebung/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/sebastian/PycharmProjects/Easyheb/neueumgebung/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/sebastian/PycharmProjects/Easyheb/neueumgebung/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-mailbox'

Why?

**Comment by ad-m** [comment]
Use ```django_mailbox``` instead of ```django-mailbox```. See https://django-mailbox.readthedocs.io/en/latest/topics/installation.html .
