### ISSUE TITLE
Admin error when using some file storage backends

### ISSUE THREAD

**Issue by machakux** [coddingtonbear/django-mailbox#302]
`NotImplementedError: This backend doesn't support absolute paths` is raised when opening e-mail messages with attachments in admin interface when using some remote file storage backends (via [ django-storages](https://pypi.org/project/django-storages/)).

I think the error is a result of trying to open attachments files directly using `open()` function; For example as in Message._rehydrate() method. 

May be a possibe soulution could be replacing direct calls to `open()` with open method from django storage backends; For example using something like `attachment.document.open('rb')`  instead of `open(attachment.document.path, 'rb')`

Sample error log 
```
Internal Server Error: /admin/django_mailbox/message/<id>/change/
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/django/db/models/options.py", line 676, in get_field
  return self.fields_map[field_name]
         ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'envelope_headers'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
  f = _get_non_gfk_field(opts, name)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
  field = opts.get_field(name)
          ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/db/models/options.py", line 678, in get_field
      raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Message has no field named 'envelope_headers'

During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
  response = get_response(request)
             ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
  response = response.render()
             ^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
  self.content = self.rendered_content
                 ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
  return template.render(context, self._request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
  return self.template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 171, in render
  return self._render(context)
         ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/test/utils.py", line 114, in instrumented_test_render
  return self.nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
  return compiled_parent._render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/test/utils.py", line 114, in instrumented_test_render
  return self.nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
  return compiled_parent._render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/test/utils.py", line 114, in instrumented_test_render
  return self.nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
  result = block.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
  result = block.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 243, in render
  nodelist.append(node.render_annotated(context))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 210, in render
  return template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 173, in render
  return self._render(context)
         ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/test/utils.py", line 114, in instrumented_test_render
  return self.nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 550, in render
  return self.nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 243, in render
  nodelist.append(node.render_annotated(context))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 243, in render
  nodelist.append(node.render_annotated(context))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 327, in render
  return nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 327, in render
  return nodelist.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
  return SafeString("".join([node.render_annotated(context) for node in self]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
  return SafeString("".join([node.render_annotated(context) for node in self]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
  return self.render(context)
         ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1067, in render
  output = self.filter_expression.resolve(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 718, in resolve
  obj = self.var.resolve(context)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 850, in resolve
  value = self._resolve_lookup(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 917, in _resolve_lookup
  current = current()
            ^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/helpers.py", line 275, in contents
  f, attr, value = lookup_field(field, obj, model_admin)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
  value = attr(obj)
          ^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django_mailbox/admin.py", line 76, in envelope_headers
  email = msg.get_email_object()
          ^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django_mailbox/models.py", line 798, in get_email_object
  self._email_object = self._rehydrate(flat)
                       ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django_mailbox/models.py", line 699, in _rehydrate
  self._rehydrate(part)
File "/usr/local/lib/python3.11/site-packages/django_mailbox/models.py", line 728, in _rehydrate
  with open(attachment.document.path, 'rb') as f:
            ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 65, in path
  return self.storage.path(self.name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/core/files/storage/base.py", line 137, in path
  raise NotImplementedError("This backend doesn't support absolute paths.")

NotImplementedError: This backend doesn't support absolute paths

```

**Comment by jordanambra** [comment]
I can confirm that this is also happening to me, using django-storages and S3/Boto, after upgrading from an older version.

It seems like it changed beginning in 4.10.0, looking at this commit: https://github.com/coddingtonbear/django-mailbox/commit/7e250b2504a9510a46ef601b25ab1907719f9e3f

@martinmanzo any thoughts on why this had to move to using `open()` instead of `attachment.document.read()`?

**Comment by pfouque** [comment]
Hi @jordanambra,
Thanks for your feedback, According to PR #273 there was an issue when too many files were opened.
I assume it was solved by using "with" which garantee to have only one file opened at once.
There is an open PR #303 that tries to solve this, but it's only rollbacking but doesn't consider the #273 issue.
Maybe you can contribute to this PR or open a new one to solve both issues at once.

**Comment by martinmanzo** [comment]
Hi @jordanambra, I was having OS errors due to files not being closed after being read and that solution did it for me.

BTW I think you may be right, `open(attachment.document.path, 'rb')` could be changed for something like:
```python
raw = attachment.document.read()
attachment.document.close()
encode_quopri(BytesIO(raw), output, quotetabs=True, header=False)
```
And the same for the other changes in 7e250b2504a9510a46ef601b25ab1907719f9e3f

Please note that I was using this in Django 3. Maybe the new versions `read()` closes the file.

Regards 💪

**Comment by pfouque** [comment]
> Please note that I was using this in Django 3. Maybe the new versions read() closes the file.

I don't think so. 

Indeed closing it explicitly should work but maybe we can also use it as a context manager:

```
with attachment.document.open() as f:
    encode_quopri(BytesIO(f.read()), output, quotetabs=True, header=False)
```

Both solutions should work!

@martinmanzo & @jordanambra can you give it a try to check both your issues are solved? 🙏

**Comment by martinmanzo** [comment]
Sure, I'll need a couple of days to free some time and give it a go.

**Comment by pfouque** [comment]
Hi @jordanambra & @martinmanzo,
Thanks to @badziyoussef, this issue is about to be tackled in #303 !
Can I ask you for some help to check it works fine for both of your issues 🙏 
That would be really helpful
