### ISSUE TITLE
Python 3 path issue with local maildir (and possibly other local file-based) mailboxes

### ISSUE THREAD

**Issue by leifurhauks** [coddingtonbear/django-mailbox#58]
I can't get messages from a local maildir Mailbox for django_mailbox 4.4.2 with python3 on linux:

```python
>>> from django_mailbox.models import Mailbox
>>> from mailbox import Maildir
>>> from email.message import Message
>>> maildir = Maildir('/tmp/maildir')
>>> mailbox = Mailbox.objects.create(uri='maildir:///tmp/maildir')
>>> msg = Message()
>>> msg.set_payload('testing 123')
>>> msg['Subject'] = 'Testing One Two Three'
>>> maildir.add(msg)
'1437492223.M426964P22857Q1.leifurpc'
>>> mailbox.get_new_mail()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/leifur/.virtualenvs/temp/lib/python3.4/site-packages/django_mailbox/models.py", line 399, in get_new_mail
    for message in connection.get_message(condition):
  File "/home/leifur/.virtualenvs/temp/lib/python3.4/site-packages/django_mailbox/transports/generic.py", line 20, in get_message
    repository = self.get_instance()
  File "/home/leifur/.virtualenvs/temp/lib/python3.4/site-packages/django_mailbox/transports/maildir.py", line 9, in get_instance
    return self._variant(self._path, None)
  File "/usr/lib64/python3.4/mailbox.py", line 272, in __init__
    'tmp': os.path.join(self._path, 'tmp'),
  File "/home/leifur/.virtualenvs/temp/lib/python3.4/posixpath.py", line 89, in join
    "components") from None
TypeError: Can't mix strings and bytes in path components
```

The probem appears to be due to the fact that `GenericFileMailbox` is passing the path as a bytestring to `mailbox.Maildir` (see  [`django_mailbox.transports.generic`](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/transports/generic.py) line 12; on py3, str.encode returns a bytestring ). Bytestring paths are allowed in python 3, but `mailbox.Maildir` in the standard library is calling `os.path.join` on the path with string literals, which (at list on *nix) causes the `TypeError` about mixing strings and bytes.

```python
# mailbox.Maildir
class Maildir(Mailbox):
    """A qmail-style Maildir mailbox."""

    colon = ':'

    def __init__(self, dirname, factory=None, create=True):
    """Initialize a Maildir instance."""
    Mailbox.__init__(self, dirname, factory, create)
    self._paths = {
        'tmp': os.path.join(self._path, 'tmp'),
        'new': os.path.join(self._path, 'new'),
        'cur': os.path.join(self._path, 'cur'),
        }
    ...
```

**Comment by coddingtonbear** [comment]
Fixed using your submitted pull request (#59), merged as 55be6b3, and released in 4.4.3.
