### ISSUE TITLE
UnicodeDecodeError in MessageAttachment

### ISSUE THREAD

**Issue by antcorro** [coddingtonbear/django-mailbox#63]
Hi.
`MessageAttachment._get_rehydrated_headers` raises a *UnicodeDecodeError* if `self.headers` contains non ASCII characters not decoded. (in Python2.x)
So if attachment file name is ð̞oβ̞le.jpg , this header is ok:
`Content-Type: image/jpeg; name="=?UTF-8?B?4oCYw7DMnm/OssyebGUuanBn?=" `
`Content-Transfer-Encoding: base64`
`Content-Disposition: attachment;
	filename*="utf-8''%E2%80%98%C3%B0%CC%9E%6F%CE%B2%CC%9E%6C%65%2E%6A%70%67"`

where this header raises *UnidoceDecodeError*:
`Content-Type: image/jpeg; name="‘ð̞oβ̞le.jpg"`
`Content-Transfer-Encoding: base64`
`Content-Disposition: attachment;
	filename*="‘ð̞oβ̞le.jpg"`

**Comment by ad-m** [comment]
@antcorro, do you can create test for this case to avoid regression?

**Comment by antcorro** [comment]
Sorry for the delay. 
I have created the test for this case.

**Comment by dmippoltiov** [comment]
Hello! We have similar problem with _get_rehydrated_headers..  Sadly this fix doesnt affect our case:
```python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/leha/django/incident/management/commands/new_get_mail.py", line 56, in handle
    for mail in mailbox.get_new_mail(): 
  File "/usr/local/lib/python2.7/site-packages/django_mailbox/models.py", line 397, in get_new_mail
    msg = self.process_incoming_message(message)
  File "/usr/local/lib/python2.7/site-packages/django_mailbox/models.py", line 259, in process_incoming_message
    msg = self._process_message(message)
  File "/usr/local/lib/python2.7/site-packages/django_mailbox/models.py", line 378, in _process_message
    message = self._get_dehydrated_message(message, msg)
  File "/usr/local/lib/python2.7/site-packages/django_mailbox/models.py", line 322, in _get_dehydrated_message
    attachment[key] = value
  File "/usr/local/lib/python2.7/site-packages/django_mailbox/models.py", line 754, in __setitem__
    rehydrated = self._get_rehydrated_headers()
  File "/usr/local/lib/python2.7/site-packages/django_mailbox/models.py", line 742, in _get_rehydrated_headers
    headers = unicode(headers, 'utf-8').encode('utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 1509: invalid continuation byte
```
Message for testing: 
a02a26a4aa4a98a11ebbe719da8c5becea45ab6b

**Comment by antcorro** [comment]
@dmippoltiov I think that the problem in unicode_error.eml  is the subject.
I notice the same problem in some German or Asian emails. I'm collecting info and investigating to fix this.

**Comment by coddingtonbear** [comment]
Just to make sure you're aware, the spec defininig how E-mail has to work is nearly 30 years old, so there are some limitations that we modern people probably wouldn't expect.  One of them is that a compliant e-mail message's subject must either be 7-bit ASCII or specially encoded ([in the way described here](https://docs.python.org/2/library/email.header.html)).

I *think* we properly handle decoding non-ASCII headers, but if you do find a case in which we aren't, I'd love to hear about it.

**Comment by coddingtonbear** [comment]
It doesn't look like there's anything actionable left on this ticket, so I'm going to close this.  Let me know if you think there's still something to do.

Cheers,
Adam
