### ISSUE TITLE
Unable import django_mailbox.tests.base.EmailMessageTestCase

### ISSUE THREAD

**Issue by ad-m** [coddingtonbear/django-mailbox#89]
Hello,

I would like test own signal processor (watchdogpolska/poradnia#200). Signals processors require ```Message``` instance which I would like generate from ```.eml``` file. ```django-mailbox``` provide code to generate email object (https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/tests/base.py#L68-84 ), then ```Message``` can be generated easily by ```Message.__process_message```.

I would like import ```from django_mailbox.tests.base import EmailMessageTestCase```. Unfortunately, ``` django-mailbox/django_mailbox/tests/__init__.py``` trigger loading ```django_mailbox.tests.transports.FAKE_UID_FETCH_MSG``` which fails.

Code:
```python
from django_mailbox.models import Mailbox
from django_mailbox.tests.base import EmailMessageTestCase

from letters.models import mail_process

class ReceiveEmailTestCase(EmailMessageTestCase):
    def setUp(self):
        self.mailbox = Mailbox.objects.create(from_email='from@example.com')
        super(TestCase, self).setUp()

    def test_cc_message(self):
        message = self._get_email_object('cc_message.eml')
        msg = self.mailbox._process_message(message)
        mail_process(sender=self.mailbox, message=msg)

```

Traceback:
```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/adas/Devel/poradnia/poradnia/letters/tests/test_models.py", line 7, in <module>
    from django_mailbox.tests.base import EmailMessageTestCase
  File "/home/adas/.virtualenvs/poradnia/local/lib/python2.7/site-packages/django_mailbox/tests/__init__.py", line 4, in <module>
    from .test_transports import *
  File "/home/adas/.virtualenvs/poradnia/local/lib/python2.7/site-packages/django_mailbox/tests/test_transports.py", line 30, in <module>
    get_email_as_text('generic_message.eml')
  File "/home/adas/.virtualenvs/poradnia/local/lib/python2.7/site-packages/django_mailbox/tests/base.py", line 25, in get_email_as_text
    'rb'
IOError: [Errno 2] No such file or directory: '/home/adas/.virtualenvs/poradnia/local/lib/python2.7/site-packages/django_mailbox/tests/messages/generic_message.eml'
```

**Comment by ad-m** [comment]
I closed that, but I would like mark that your load a few messages to memory even if you don't need them. Due global definition it will be never removed from memory.
