### ISSUE TITLE
Collecting mail issues python 3.4 (happend on specific mails)

### ISSUE THREAD

**Issue by gerdkoetje** [coddingtonbear/django-mailbox#97]
Traceback (most recent call last):
  File "/srv/webapps/promo/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/webapps/promo/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/webapps/promo/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/webapps/promo/venv/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/webapps/promo/venv/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/srv/webapps/promo/venv/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/webapps/promo/src/django_mailbox/management/commands/getmail.py", line 30, in handle
    messages = mailbox.get_new_mail()
  File "/srv/webapps/promo/src/django_mailbox/models.py", line 374, in get_new_mail
    msg = self.process_incoming_message(message)
  File "/srv/webapps/promo/src/django_mailbox/models.py", line 220, in process_incoming_message
    msg = self._process_message(message)
  File "/srv/webapps/promo/src/django_mailbox/models.py", line 355, in _process_message
    message = self._get_dehydrated_message(message, msg)
  File "/srv/webapps/promo/src/django_mailbox/models.py", line 244, in _get_dehydrated_message
    self._get_dehydrated_message(part, record)
  File "/srv/webapps/promo/src/django_mailbox/models.py", line 267, in _get_dehydrated_message
    filename = utils.convert_header_to_unicode(msg.get_filename())
  File "/srv/webapps/promo/src/django_mailbox/utils.py", line 79, in convert_header_to_unicode
    ) for bytestr, encoding in email.header.decode_header(header)
  File "/usr/lib/python3.4/email/header.py", line 80, in decode_header
    if not ecre.search(header):
TypeError: expected string or buffer
root@promo:/var/lib/postgresql/9.3/main/pg_

LOCAL

  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/igeni/promonew/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/igeni/promonew/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/igeni/promonew/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/igeni/promonew/lib/python3.5/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/Users/igeni/promonew/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/management/commands/getmail.py", line 30, in handle
    messages = mailbox.get_new_mail()
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/models.py", line 374, in get_new_mail
    msg = self.process_incoming_message(message)
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/models.py", line 220, in process_incoming_message
    msg = self._process_message(message)
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/models.py", line 355, in _process_message
    message = self._get_dehydrated_message(message, msg)
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/models.py", line 244, in _get_dehydrated_message
    self._get_dehydrated_message(part, record)
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/models.py", line 267, in _get_dehydrated_message
    filename = utils.convert_header_to_unicode(msg.get_filename())
  File "/Users/igeni/Documents/DJANGO-PROJECTEN/promo/django_mailbox/utils.py", line 79, in convert_header_to_unicode
    ) for bytestr, encoding in email.header.decode_header(header)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/header.py", line 80, in decode_header
    if not ecre.search(header):
TypeError: expected string or bytes-like object

**Comment by coddingtonbear** [comment]
Could you upload the e-mail message that caused this problem, @gerdkoetje and let me know what version of Django Mailbox you're currently using?

**Comment by gerdkoetje** [comment]
4.4.8 sorry i cant get the mail it got deleted

**Comment by coddingtonbear** [comment]
I was *just* about to say that there's very little troubleshooting that can be done without a sample e-mail, but i think the traceback you attached shows at least a ~reasonably likely culprit.  I've made a change in release 4.5.1 just a few minutes ago.  Give it a shot and comment on this issue if the issue is still  occurring after upgrading!

Cheers,
Adam
